### ISSUE TITLE
Start service issue.

### ISSUE THREAD

**Issue by lzbj** [vaporz/turbo#35]
I create a test grpc service by run command like this:

turbo create turbo TestService -r grpc, then run go run main.go under TestService, got following problem:

turbo/gen
gen/grpcswitcher.go:21:76: cannot use callOptions (type []"github.com/vaporz/turbo/vendor/google.golang.org/grpc".CallOption) as type []"vendor/google.golang.org/grpc".CallOption in argument to s.Service().("turbo/gen/proto".TestServiceClient).SayHello

**Comment by vaporz** [comment]
Because the compiler found two CallOption under: 
1, "github.com/vaporz/turbo/vendor/google.golang.org/grpc", which is in turbo's vendor,
2, "vendor/google.golang.org/grpc", which is in the vendor in you GOPATH.

2 methods to fix this problem:
1, delete one of the vendor folders above,
2, add vendor folder to your new service, and copy all dependency to the service's own vendor.

I recommend method 2.
