### ISSUE TITLE
How to use map<string, string> in MethodNameRequest?

### ISSUE THREAD

**Issue by tys920** [vaporz/turbo#50]
I defined the variable map<string,string> in the engine .proto , but when I start grpcswitcher.go it prompts an error: ..\gen\grpcswitcher.go:24:35: unknown field 'Rms' in struct literal of type "kubeensaas-engine/gen/proto".SayHelloRequest.

engine .proto:

`service Engine {
  rpc Deploy (DeployRequest) returns (DeployResponse) {}
  rpc sayHello (SayHelloRequest) returns (SayHelloResponse) {}
}

message SayHelloRequest {
  string yourName = 1;
  map<string, string> rms = 2;
}`

grpcswitcher.go:

`case "SayHello":
	request := &g.SayHelloRequest{ Rms: &g.RmsEntry{}, }

	err = turbo.BuildRequest(s, request, req)

	if err != nil {
		return nil, err
	}

	rpcResponse, err = s.Service("Engine").(g.EngineClient).SayHello(req.Context(), request, callOptions...)`

**Comment by vaporz** [comment]
Sorry, Turbo doesn't support map. Turbo only support slices except fundamental types.
The reason is, there isn't a common practice on how to present a map in query string.
But as a workaround, you can seperate a map into two slices: keys and values.
For example: ?keys=k1,k2,k3&values=v1,v2,v3
Then change the message definition into this:
`message SayHelloRequest {
string yourName = 1;
repeated string keys = 2;
repeated string values = 3;
}`

**Comment by tys920** [comment]
> Sorry, Turbo doesn't support map. Turbo only support slices except fundamental types.
> The reason is, there isn't a common practice on how to present a map in query string.
> But as a workaround, you can seperate a map into two slices: keys and values.
> For example: ?keys=k1,k2,k3&values=v1,v2,v3
> Then change the message definition into this:
> 
> `
> message SayHelloRequest {
> 
> ```
>     string yourName = 1;
> 
>     repeated string keys = 2;
> 
>     repeated string values = 3;
> 
> }`
> ```

Ok，I understand ！Thanks.
